### ISSUE TITLE
Cannot convert undefined or null to Object in line 102 index.js

### ISSUE THREAD

**Issue by sergiottomas** [xioup/underscoreDeepExtend#18]
Hello Kurt, your code not working in my application when gulp is executed an exception is called on line 102 in index.js

**Cannot convert undefined or null to Object line 102**

I solved this using conditional after line 101.

extendObject = function(src) {
        source = src;
        if(source){
          Object.keys(source).forEach(procMain);          
        }
      };

but, I dont know if this is correctly way to fix this issue.

**Comment by kurtmilam** [comment]
I guess this happens when one of the parameters you pass into the outer function is `undefined` or `null`?

If that's correct, I think the best  solution would be for you to add the check outside of the function, i.e. don't pass `undefined` or `null` into a function that expects all parameters to be objects.

If that's incorrect, please show me a short example of code that causes this error to be thrown.
